# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_inventory', '0002_auto_20171024_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(max_length=50),
        ),
    ]
