# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_inventory', '0005_auto_20171031_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([]),
        ),
    ]
